spring:
  application:
    name: eventplatform
  redis:
    host: localhost
    port: 6379
  postgreSQL:
    host: localhost
    port: 5432

jwt:
  access_token:
    valid_time: 60000 # 10분
  refresh_token:
    valid_time: 7200000 # 2시간
  secret: thisismysecretforjwt.needtoover32bytesmaybe.butthissample