spring:
  application:
    name: eventplatform
  thread.virtual.enabled: true # virtual thread 활성화 (Java 21 이상)

  # DB (PostgreSQL) 설정
  datasource:
    driver-class-name: org.postgresql.Driver
    # Podman 컴포즈와 로컬 호환을 위해 환경 변수 처리
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/eventdb?options=-c%20statement_timeout=5000%20-c%20lock_timeout=3000}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
    hikari:
      connection-timeout: 3000 # 파이프를 얻기 위해 대기하는 시간 (3초)
      maximum-pool-size: 10
      max-lifetime: 1800000
      idle-timeout: 600000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        default_schema: public
      jakarta.persistence.query.timeout: 5000 # 쿼리 실행 제한 시간 (5초, ms 단위)

  # Redis (대기열 및 키 만료 이벤트) 설정
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost} # Podman 컴포즈 환경 대응
      port: 6379

  # Kafka (비동기 Job 워커 큐) 설정
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    consumer:
      group-id: event-worker-group
      auto-offset-reset: earliest
      enable-auto-commit: false # 수동 오프셋 커밋을 위해 false 설정
    listener:
      ack-mode: manual_immediate # 워커에서 ack.acknowledge() 쓰기 위해 필수 설정

  docker:
    compose:
      enabled: false

# JWT 설정
jwt:
  access_token:
    valid_time: 600000 # 10분
  refresh_token:
    valid_time: 7200000 # 2시간
  secret: thisismysecretforjwt.needtoover32bytesmaybe.butthissample
  entry_token_secret: thisisentry_token_secretforjwt.needtoover32bytes.butthisisample

logging:
  level:
    root: info
    org.hibernate.SQL: debug