spring:
  application:
    name: eventplatform
  redis:
    host: localhost
    port: 6379
  # DB
  datasource:
    driver-class-name: org.postgreSql.Driver
    url: jdbc:postgresql://localhost:5432/mydatabase
    platform: postgres
    username: myuser
    password: secret
  jpa:
    hibernate: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  kafka:
    host: localhost
    port: 9092

jwt:
  access_token:
    valid_time: 60000 # 10분
  refresh_token:
    valid_time: 7200000 # 2시간
  secret: thisismysecretforjwt.needtoover32bytesmaybe.butthissample

logging:
  level:
    root: info